# iptable configuration
#
# all ports will be blocked, except the ports listed below
iptables:
  accept:
    -
      port: 22
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 80
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 1883
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 1884
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 8080
      source: 0.0.0.0/0
      protocol: tcp
    -
      port: 1700
      source: 0.0.0.0/0
      protocol: udp

# mosquitto configuration (MQTT)
#
# this defines the listeners (and protocols) and the usernames that
# are allowed to connect to the MQTT broker and to which MQTT topics
# they are restricted
mosquitto:
  listeners:
    -
      bind_address: 0.0.0.0
      bind_port: 1883
      protocol: mqtt
    -
      bind_address: 0.0.0.0
      bind_port: 1884
      protocol: websockets
  users:
    -
      user: loraserver_gw
      password: loraserver_gw
      topics:
        - write gateway/+/stats
        - write gateway/+/rx
        - read gateway/+/tx
        - read gateway/+/config
    -
      user: loraserver_ns
      password: loraserver_ns
      topics:
        - write gateway/+/tx
        - write gateway+/config
        - read gateway/+/stats
        - read gateway/+/rx
        - read gateway/+/ack
    -
      user: loraserver_as
      password: loraserver_as
      topics:
          - write application/+/device/+/rx
          - write application/+/device/+/join
          - write application/+/device/+/ack
          - write application/+/device/+/error
          - write application/+/device/+/status
          - write application/+/device/+/location
          - read application/+/device/+/tx
    -
      user: loraserver_app
      password: loraserver_app
      topics:
        - write application/+/device/+/tx
        - read application/+/device/+/rx
        - read application/+/device/+/join
        - read application/+/device/+/ack
        - read application/+/device/+/error
        - read application/+/device/+/status
        - read application/+/device/+/location

# postgresql configuration
#
# this defines the databases that will be created and the credentials to
# connect to these databases
postgresql:
  databases:
    -
      name: loraserver_as
      user: loraserver_as
      password: loraserver_as
    -
      name: loraserver_ns
      user: loraserver_ns
      password: loraserver_ns

# lora-app-server configuration
lora_app_server:
  letsencrypt:
    domain: example.com
    email: info@example.com
    accept_letsencrypt_tos: False
