- name: install chirpstack-application-server
  package:
    name: chirpstack-application-server
    state: latest

- name: copy configuration
  template:
    src: chirpstack-application-server.toml
    dest: /etc/chirpstack-application-server/chirpstack-application-server.toml
    owner: appserver
    group: appserver
    mode: 0640
  notify:
    - restart chirpstack-application-server

- name: request letsencrypt certificate
  command: certbot --nginx certonly --non-interactive --agree-tos -m {{ chirpstack_application_server.letsencrypt.email }} -d {{ chirpstack_application_server.fqdn }}
  when: chirpstack_application_server.letsencrypt.request

- name: add nginx proxy
  template:
    src: chirpstack-application-server.nginx
    dest: /etc/nginx/sites-enabled/chirpstack-application-server
  notify:
    - reload nginx

- name: start chirpstack-application-server on boot
  service:
    name: chirpstack-application-server
    state: started
    enabled: yes
